name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Yarn Dependencies
      uses: Borales/actions-yarn@master
      with:
        args: install
    - name: Build Frontend
      run: yarn prod
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: Run Test Suite
      run: vendor/bin/phpunit
